### ISSUE TITLE
npm install gulp-aws fetches out of date version of the package

### ISSUE THREAD

**Issue by robertpataki** [spreaker/gulp-aws#10]
When running `npm install gulp-aws` I can see that it installs `gulp-aws@0.0.4`, but I am hitting this old issue: [https://github.com/spreaker/gulp-aws/issues/3](https://github.com/spreaker/gulp-aws/issues/3). It would be nice to have this package up to date in the npm directory as well please.

**Comment by pracucci** [comment]
Thanks for reporting it. I just released the version `0.0.5` from `master`.
